Nv7-GitHub/Nv7Haven

eod/info.go

was this supposed to take more coding

Add sort by Creator to /elemsort

---

eod/randcmd.go

First time programming with go. Hope I didn't make any mistakes

Check to make sure idea has at least 2 elements

---

eod/catchange.go

Fix a typo

---

eod/categories.go

this is a very nice PR that should work as far as I know

add vukky autocat

---

eod/suggest.go

[EoDE] remove zero width characters from suggestions

---

eod/info.go

<t:timestamp:f> shows the date in the format January 1, 1970 00:00 (with modifications based on the timezone/format settings of the device)

Use discord timestamp conversion functionality

---

nv7haven/other.go

I have no idea how to run a Go server so I can only hope this works :stuck_out_tongue: 
(no, but seriously, this would be so embarrassing if I did something wrong)

Hopefully fix the YouTube Downloader

---

eod/info.go

anyone can change it with a vote

Rename creator mark to mark

---

discord/currency.txt

propr -> prop (which is what the actual command is)

Change help text for currency

---

eod/cmdhandlers.go

adds !top and !leaderboard as aliases for !lb and adds !elements as an alias for !inv

Add some command aliases from the original Elemental Bot

---

eod/translation/languages/es_mx.json

IDCannotBeNegative, ComboNoExist, PollNoExist

things sight asked me to translate

---

eod/translation/languages/in.json

Fixed Problem with NewComboNews and NewElemNews in the Indonesian Translation

---

eod/elements/suggest.go

ban special time code thing in element names

---

eod/translation/languages/in.json

oops (Fixed   "SuggestedElem")

---

eod/slashcmds.go

a hex code must be 6 digits long

---

eod/base/util.go
eod/categories/get.go
eod/elements/info.go

we didn't need them there in the first place

[EoD] remove vcats from element info

---

eod/elements/hints.go

there's an entire unused check so i'm gonna use it by changing the conditions under which it triggers to ones that actually work

Make inverse hint not freak out when not given an argument

---

eod/elements/hints.go

it was applying to regular hint and not inverse hint :/

Fix inverse hint no argument check

---

eod/elements/hints.go

actually using hasElem in !ih this time

Actually fix !ih

---

discord/currency.txt
discord/properties.go

See a user's income/second and money in limbo. I'm pretty sure this won't have errors because most of it is a compilation of other commands :P
Watch how there is an error though
On second thought don't accept this until you get back from I'm assuming camp in case I crash your server lol
So um
Yeah
This will be useful in my quest to CONQUER Nv7 Haven with my wealth
Kindly ignore the above message
It was definitely a joke
I don't know why I'm still talking
I'm really tired right now it's like 1:30 I need sleep aaaaaaaaaaaaaaaa

Add "income" Command

---

discord/properties.go

Currently it will return your income even if you specify another user I am very dumb 🤣

Bugfix `income`

---

eod/elements/deletecmd.go
eod/elements/elements.go

Deletes all combos except for the oldest combo. Recalculates tree size.
please dont wait 6 months this time smh

Delete combos command

---

eod/msgs.go

updated version of #148
closes #148

Add optional query argument to !next (updated)

---

eod/msgs.go

i have no idea if this will work

color text command + !c for category

---

eod/elements/hint.go
eod/elements/next.go

Make hint and next have image and element color

---

eod/msgs.go

formatting should optimally be like !color e black|000000 but this works for now

Element/Category/Query Signifiers for !sign and !color

---

eod/msgs.go

Correct amount of parts for !sign

---

eod/categories/infoedit.go
eod/msgs.go
eod/queries/edit.go

this should work now FINALLY!!!!!!

MsgSignCmd compatibility for categories and queries

---

eod/categories/infoedit.go
eod/queries/edit.go

idk how to make these into one big PR sorry for the number bloat

sign command works now FOR REALLL MAYBE

---

eod/msgs.go
eod/sorts.go

Fixing adding 0 elements !ac bug. Making ping use server acknowledge time difference. Adding !invhint as another alias of products

!ac bug fix

---

eod/categories/info.go
eod/elements/info.go
eod/queries/info.go
eod/sorts.go

Fixing !ac bug (fully this time) Making info actually acknowledge. Making color field appear on element info, query info and cat info. Adding emoji for element mark field and color field and changing emoji of element colorer.

Fixing !ac and adding color to info

---

eod/pages/pages.go

Fixing postfix spacing from #160

Postfix spacing

---

eod/msgs.go

april foul

---

eod/base/querycalc.go
eod/categories/infoedit.go
eod/elements/idea.go
eod/pages/queries.go
eod/polls/querysuccess.go
eod/queries/delete.go

* fixing non distinct idea bug
* fixing category query bug
* slightly simplifying idea code

More bug fixes 

---

eod/msgs.go

ID imaging

---

eod/categories/infoedit.go
eod/elements/edit.go
eod/msgs.go
eod/queries/edit.go

change it to say mark instead of note. Adding note as an alias for mark

Mark Consistency

---

eod/elements/hint.go
eod/elements/next.go
eod/pages/elemcats.go
eod/pages/elemfound.go
eod/pages/products.go

now displays element ID in hint,next,products,elemfound and elemcats

Adding element ID to more places
